### ISSUE TITLE
Unexpected reserved word

### ISSUE THREAD

**Issue by franfram** [huntabyte/chatty#3]
Hello, amazing repo and vid. 

I'm running into the following error when running `npm create svelte@latest`:

```
file:///home/user/.npm/_npx/50a6160ffc29bafc/node_modules/create-svelte/bin.js:19
	const dir = await p.text({
	            ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
npm ERR! code 1
npm ERR! path /home/user/chatty
npm ERR! command failed
npm ERR! command sh -c create-svelte

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2023-03-09T07_40_03_462Z-debug-0.log
```
Any ideas how can I fix it?
Thanks

**Comment by huntabyte** [comment]
@franfram Thank you! Curious why are you running `npm create svelte@latest` ? 

The app is already created, you just need to install the dependencies with `npm i` and then run the dev server with `npm run dev`

**Comment by franfram** [comment]
Yeah, My Bad. Thanks

**Comment by huntabyte** [comment]
@franfram no problem!
