### ISSUE TITLE
font error[FATAL ERROR]

### ISSUE THREAD

**Issue by nekohacker591** [huntabyte/chatty#6]
D:\AI\npm2\chatty>npm run dev -- --open

> chatty@0.0.1 dev
> vite dev --open

  VITE v4.1.4  ready in 1228 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
11:01:36 AM [vite-plugin-svelte] ssr compile in progress ...

🌼 daisyUI components 2.51.3  https://daisyui.com
  ✔︎ Including:  base, components, 29 themes, utilities
  ❤︎ Support daisyUI:  https://opencollective.com/daisyui

[postcss] Failed to find '@fontsource/fira-mono'
  in [
    D:/AI/npm2/chatty/src/routes
  ]
Internal server error: [postcss] Failed to find '@fontsource/fira-mono'
  in [
    D:/AI/npm2/chatty/src/routes
  ]
  Plugin: vite:css
  File: D:/AI/npm2/chatty/src/routes/styles.css:undefined:undefined
      at file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-53dc1ef4.js:93:13
      at async Promise.all (index 0)
      at async LazyResult.runAsync (D:\AI\npm2\chatty\node_modules\postcss\lib\lazy-result.js:396:11)
      at async compileCSS (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:36736:25)
      at async TransformContext.transform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:36197:56)
      at async Object.transform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
      at async loadAndTransform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29)
Error: [postcss] Failed to find '@fontsource/fira-mono'
  in [
    D:/AI/npm2/chatty/src/routes
  ]
    at file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-53dc1ef4.js:93:13
    at async Promise.all (index 0)
    at async LazyResult.runAsync (D:\AI\npm2\chatty\node_modules\postcss\lib\lazy-result.js:396:11)
    at async compileCSS (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:36736:25)
    at async TransformContext.transform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:36197:56)
    at async Object.transform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
    at async loadAndTransform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29)
Internal server error: [postcss] Failed to find '@fontsource/fira-mono'
  in [
    D:/AI/npm2/chatty/src/routes
  ]
  Plugin: vite:css
  File: D:/AI/npm2/chatty/src/routes/styles.css:undefined:undefined
      at file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-53dc1ef4.js:93:13
      at async Promise.all (index 0)
      at async LazyResult.runAsync (D:\AI\npm2\chatty\node_modules\postcss\lib\lazy-result.js:396:11)
      at async compileCSS (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:36736:25)
      at async TransformContext.transform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:36197:56)
      at async Object.transform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
      at async loadAndTransform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29) (x2)
Error: [postcss] Failed to find '@fontsource/fira-mono'
  in [
    D:/AI/npm2/chatty/src/routes
  ]
    at file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-53dc1ef4.js:93:13
    at async Promise.all (index 0)
    at async LazyResult.runAsync (D:\AI\npm2\chatty\node_modules\postcss\lib\lazy-result.js:396:11)
    at async compileCSS (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:36736:25)
    at async TransformContext.transform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:36197:56)
    at async Object.transform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
    at async loadAndTransform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29)
Error: Not found: /favicon.ico
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:394:13)
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:243:5)
    at #options.hooks.handle (/@fs/D:/AI/npm2/chatty/node_modules/@sveltejs/kit/src/runtime/server/index.js:41:55)
    at Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:240:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Internal server error: [postcss] Failed to find '@fontsource/fira-mono'
  in [
    D:/AI/npm2/chatty/src/routes
  ]
  Plugin: vite:css
  File: D:/AI/npm2/chatty/src/routes/styles.css:undefined:undefined
      at file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-53dc1ef4.js:93:13
      at async Promise.all (index 0)
      at async LazyResult.runAsync (D:\AI\npm2\chatty\node_modules\postcss\lib\lazy-result.js:396:11)
      at async compileCSS (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:36736:25)
      at async TransformContext.transform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:36197:56)
      at async Object.transform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
      at async loadAndTransform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29) (x3)
Error: [postcss] Failed to find '@fontsource/fira-mono'
  in [
    D:/AI/npm2/chatty/src/routes
  ]
    at file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-53dc1ef4.js:93:13
    at async Promise.all (index 0)
    at async LazyResult.runAsync (D:\AI\npm2\chatty\node_modules\postcss\lib\lazy-result.js:396:11)
    at async compileCSS (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:36736:25)
    at async TransformContext.transform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:36197:56)
    at async Object.transform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
    at async loadAndTransform (file:///D:/AI/npm2/chatty/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29)

**Comment by huntabyte** [comment]
No context provided beyond an error message.
